name: C/C++ CI

on:
  push:

jobs:
  build-and-test:
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v2
      - name: install cppunit
      run: sudo apt install -y libcppunit-dev
      - name: make
      run: make

name: Build
