name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git g++ -i --verbose CPP/ip_calc.cpp CPP/TRPO.cpp Headels/ip_calc.h && git diff --exit-code

      - name: Build application
        run: make
