name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{cpp,h} -iname *.cpp | xargs clang-format -i

      - name: Build application
        run: make
